### ISSUE TITLE
End time is saving as 5:30 when only hour is given.

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#100]
**Reproducible Steps**
1.Login with valid credential.
2.Go to add task.
3.Give the start time and end time as 10
4.Click on save

**Observation**
- End time is saving as 5:30

**Expectation**
- End time should not save as 5:30 when only hour is given.
![Capture525222](https://user-images.githubusercontent.com/41984345/75132359-ab113380-56fc-11ea-822b-4acbf8e0d94b.PNG)

**After save**
![Capture225562522](https://user-images.githubusercontent.com/41984345/75132570-69cd5380-56fd-11ea-82eb-516f1fc745a9.PNG)
![Capture256363](https://user-images.githubusercontent.com/41984345/75132567-676af980-56fd-11ea-8391-3c5412a07d22.PNG)

**Comment by Sujatagp** [comment]
In current release if we give only hour it is working as expected hence moving to closed list.
