### ISSUE TITLE
Not able to save the task after giving invalid end time and then valid end time.

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#101]
**Reproducible Steps**
1.Login with valid credential.
2.Create a task.
3.Give valid start time and invalid end time.
4.Click on save.
5.Now give valid end time.

**Observation**
- Cannot save after giving valid end time.Error message stating "Start/end time cannot greater than current time"is displaying.

**Expectation**
- Should able to save the task after giving valid end time.
![Capture125566](https://user-images.githubusercontent.com/41984345/75133719-cb8fbc80-5701-11ea-9beb-cfa50e3406dd.PNG)
![Capture25252](https://user-images.githubusercontent.com/41984345/75133725-cfbbda00-5701-11ea-9a5d-020ede88c9bf.PNG)

**Comment by Sujatagp** [comment]
This is still showing same error.

**Comment by Sujatagp** [comment]
In current release it is working as expected hence moving to closed list.
