### ISSUE TITLE
Should stop all the running tasks if user punched out

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/TimeTracker#103]
**Steps to reproduce**

1. Login to time tracker.
2. Punch in and add tasks.
3. Click on pinch out without stopping tasks.

**Expectation**
Should ask users to stop running tasks or should automatically stop the tasks if user punch out.

**Observation**
Tasks will be still running after punch out also and we cannot stop after punch out.

**Comment by gpashis** [comment]
@vinay-km Lets change the design for punch out also.

![image](https://user-images.githubusercontent.com/697210/78376633-38914e80-75ec-11ea-91df-3633ae276ec2.png)

**Comment by Sujatagp** [comment]
We should not allow to add punch out time which is greater than current time

**Comment by Sujatagp** [comment]
In current release not allowing to add punch out time which is greater than current time.

<img width="1273" alt="Screen Shot 2020-04-23 at 11 37 38 AM" src="https://user-images.githubusercontent.com/41627571/80064977-f1e1a500-8556-11ea-91b6-ace892cc8f6d.png">
