### ISSUE TITLE
Retaining the form values on error

### ISSUE THREAD

**Issue by gpashis** [IncendiaryCode/TimeTracker#107]
Retain email address entered if there are any errors on login.

![image](https://user-images.githubusercontent.com/697210/75225736-378d2600-57d1-11ea-95cf-6161af2f1f03.png)

**Comment by Sujatagp** [comment]
In current release retaining the value entered if there are any error. Working as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-02 at 5 22 29 PM" src="https://user-images.githubusercontent.com/41627571/78246563-fa6e2f00-7506-11ea-879c-fd5b2556f7a3.png">
