### ISSUE TITLE
pagination in user dashboard.

### ISSUE THREAD

**Issue by vinay-km** [IncendiaryCode/TimeTracker#122]

**Comment by Sujatagp** [comment]
Pagination is given at user dashboard if there are more than 50 tasks. Working as expected hence moving to closed list.

<img width="1279" alt="Screen Shot 2020-04-06 at 4 22 28 PM" src="https://user-images.githubusercontent.com/41627571/78551432-598fb480-7823-11ea-8852-644023518684.png">
