### ISSUE TITLE
Should show error message if user tries to punch out when there are running tasks.

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/TimeTracker#128]
**Steps to reproduce**

1. Login to web timetracker.
2. Punch in for the day.
3. Add running tasks.
4. Click on punch out.

**Expectation**
Should not be allowed to punch out and should show error message as we cannot punch out before ending the tasks.

**Observation**
After clicking on punch out we are not showing any error message and not punching out also.

<img width="1274" alt="Screen Shot 2020-04-03 at 4 05 14 PM" src="https://user-images.githubusercontent.com/41627571/78354558-b42dd400-75c9-11ea-960f-eb0ca4047118.png">

**Comment by gpashis** [comment]
@vinay-km Lets add the dialog to prompt user for the error.

![image](https://user-images.githubusercontent.com/697210/78376337-cb7db900-75eb-11ea-89e1-00484d0ae1cc.png)

**Comment by Sujatagp** [comment]
In current release showing notification pop up if they try to punch out while running tasks. Working as expected hence moving to closed list.

<img width="1277" alt="Screen Shot 2020-04-06 at 4 21 00 PM" src="https://user-images.githubusercontent.com/41627571/78551281-0f0e3800-7823-11ea-87eb-f58df537fb87.png">
