### ISSUE TITLE
After deleting the timeline,clicking on+ button,timeline is not inserting.

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#25]
**Reproducible steps**
1.Login with valid credentials.
2.Add a task with  start time and end task and save it.
3.Go to same task and add one more timeline with start time and end task.
4.Delete the first timeline and click on+ button.

**Observation**
- Timeline is not getting added.

**Expectation**
- Timeline should get added after clicking on+ button.
![Capture523366](https://user-images.githubusercontent.com/41984345/73046526-807f5100-3e98-11ea-91a0-47b348dc3a79.PNG)

**Comment by Sujatagp** [comment]
If we follow the exact steps explained above it shows task name exists error and not adding new timeline.

**Comment by Sujatagp** [comment]
In current release it is working as expected hence moving to closed list.
