### ISSUE TITLE
Website change request

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#3]
- All task's timings editable.
- On hover effect everywhere for the button action.
- Avoid animations/no delay for the pop-up.
- Move down the GreenPrint name to page bottom.
- iPhone X menu issues (cropping).
- Timer & logo display in the tabs (task timer not login timer).
- Display total task time.

**Comment by vinay-km** [comment]
- In edit_task, all timings are kept editable.
- Hover property is applied to all buttons.
- Avoided animations for pop-up.
- Timer and logo is displaying in tab.
