### ISSUE TITLE
Typo should be corrected.

### ISSUE THREAD

**Issue by Sujatagp** [IncendiaryCode/TimeTracker#32]
1. Activities at dashboard.

<img width="1271" alt="Screen Shot 2020-01-27 at 12 24 13 PM" src="https://user-images.githubusercontent.com/41627571/73171446-c2252b80-4126-11ea-9f8f-397642b0d888.png">

2. Password at change password.

<img width="1277" alt="Screen Shot 2020-01-27 at 11 32 11 AM" src="https://user-images.githubusercontent.com/41627571/73171608-27791c80-4127-11ea-9e02-bf1eedd7318f.png">

**Comment by gp-purushothama** [comment]
@vinay-km please check all other places.

**Comment by Sujatagp** [comment]
In current release typo are corrected. Working as expected hence moving to closed list.
