### ISSUE TITLE
Change week number to respective date range

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#39]
![Screenshot 2020-01-30 at 11 16 59 AM](https://user-images.githubusercontent.com/8351837/73423405-0b0cf800-4352-11ea-86ed-d94525893f7e.png)

**Comment by Sujatagp** [comment]
In current release weekly UI is changed and showing date range as expected hence moving to closed list.

<img width="1278" alt="Screen Shot 2020-04-21 at 6 01 44 PM" src="https://user-images.githubusercontent.com/41627571/79866331-3c99da80-83fa-11ea-8c8b-e15515d6536b.png">
