### ISSUE TITLE
Add a filter to choose project wise tasks

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#41]

**Comment by Ganeshakumar** [comment]
![Screenshot 2020-01-30 at 11 36 16 AM](https://user-images.githubusercontent.com/8351837/73424408-bcad2880-4354-11ea-8850-30e55a61062b.png)

**Comment by Sujatagp** [comment]
@vinay-km : Filter option should be there at my activities also.

**Comment by Sujatagp** [comment]
In current release filter option is given at my activities also. Working as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-21 at 6 23 11 PM" src="https://user-images.githubusercontent.com/41627571/79868213-36f1c400-83fd-11ea-94a8-8e5795722595.png">
