### ISSUE TITLE
Show time for running tasks

### ISSUE THREAD

**Issue by anushashetty** [IncendiaryCode/TimeTracker#44]
Display since how along a task has been running in user's dashboard

**Comment by Sujatagp** [comment]
Showing time of running task at dashboard. Working as expected hence moving to closed list.

<img width="1278" alt="Screen Shot 2020-02-14 at 12 39 12 PM" src="https://user-images.githubusercontent.com/41627571/74509304-2584cb00-4f27-11ea-8e4d-4f37e3af1350.png">
