### ISSUE TITLE
Change weekly chart to stack chart with project details

### ISSUE THREAD

**Issue by anushashetty** [IncendiaryCode/TimeTracker#45]

**Comment by Sujatagp** [comment]
In weekly activities:
1. Should show hours unit at Y axis.
2. Showing 0 for tasks which we have not worked for particular day which should not show.

**Comment by Sujatagp** [comment]
In current release Working as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-01 at 4 00 46 PM" src="https://user-images.githubusercontent.com/41627571/78127623-22d82980-7432-11ea-8b1c-59017909f1bb.png">
