### ISSUE TITLE
Add total no.of hours worked in daily section of my activities

### ISSUE THREAD

**Issue by anushashetty** [IncendiaryCode/TimeTracker#46]
This is for day

**Comment by Sujatagp** [comment]
In current release added total duration for a day in daily activities. Working as expected hence moving to closed list.

<img width="1279" alt="Screen Shot 2020-02-24 at 11 37 52 AM" src="https://user-images.githubusercontent.com/41627571/75131683-3806bd80-56fa-11ea-9a6d-66e4558ecf30.png">
