### ISSUE TITLE
Change monthly chart to show calendar like display

### ISSUE THREAD

**Issue by anushashetty** [IncendiaryCode/TimeTracker#47]
Same as shown in App

**Comment by Sujatagp** [comment]
1. In monthly activities Y axis we should add hours unit.
2. The task on which we have not worked for particular day is showing 0 which would not show.

**Comment by Sujatagp** [comment]
1. Duration showing at monthly is not matching if we add duration of all days from daily activities.
2. Also mention unit for total duration at activities.

**Comment by Sujatagp** [comment]
In current release total duration is showing as expected hence moving to closed list.

<img width="1276" alt="Screen Shot 2020-04-21 at 6 32 42 PM" src="https://user-images.githubusercontent.com/41627571/79869154-9dc3ad00-83fe-11ea-835a-082f235f2598.png">
