### ISSUE TITLE
Admin Panel users page: show time separately for each project

### ISSUE THREAD

**Issue by anushashetty** [IncendiaryCode/TimeTracker#48]
Currently we have clubbed the time and shown for all projects. Instead we show it based on each project.

**Comment by Sujatagp** [comment]
In current release showing time separately for each project. Working as expected hence moving to closed list.

<img width="1276" alt="Screen Shot 2020-02-25 at 4 32 41 PM" src="https://user-images.githubusercontent.com/41627571/75241675-94e2a080-57ec-11ea-8d2b-1f1adb862e38.png">
