### ISSUE TITLE
Recent Activities Order has to be reversed.

### ISSUE THREAD

**Issue by anushashetty** [IncendiaryCode/TimeTracker#50]
Recently added should be shown on top

**Comment by Sujatagp** [comment]
Recently added task is showing at the top. Working as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-01 at 4 28 51 PM" src="https://user-images.githubusercontent.com/41627571/78129952-0b9b3b00-7436-11ea-8424-ae5618501cc1.png">
