### ISSUE TITLE
Cannot remove last timeline data

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#52]
![Screenshot 2020-02-05 at 6 02 43 PM](https://user-images.githubusercontent.com/8351837/73841982-b8e04100-4841-11ea-96a5-55101e47df36.png)

**Comment by Sujatagp** [comment]
@vinay-km : If we remove last timeline task is deleting which should not.

**Comment by gpakshith** [comment]
- We can remove the last timeline.But the task without timeline is not displaying in the Dashboard

**Comment by Sujatagp** [comment]
After deleting last timeline it shows at dashboard as yet to start. Working as expected hence moving to closed list.

<img width="1265" alt="Screen Shot 2020-04-01 at 4 07 29 PM" src="https://user-images.githubusercontent.com/41627571/78128177-1f916d80-7433-11ea-8679-13257d9f980d.png">
