### ISSUE TITLE
Updating end time in AM/PM is not saving the punch out time properly.

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#54]
- Add appropriate format placeholders for the fields like if date is in 24 hour format then mention it to the user.

**Comment by Sujatagp** [comment]
In current release showing 24 hour format at time field, working as expected hence moving to closed list

<img width="1260" alt="Screen Shot 2020-02-20 at 4 03 42 PM" src="https://user-images.githubusercontent.com/41627571/74925768-d47b4800-53fa-11ea-83c4-6c323530a958.png">

<img width="1280" alt="Screen Shot 2020-02-20 at 4 04 05 PM" src="https://user-images.githubusercontent.com/41627571/74925782-d93ffc00-53fa-11ea-8580-a02390954ba8.png">
