### ISSUE TITLE
Start a week from a Monday

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#58]
- In Week report view show days starting from Monday.

**Comment by Sujatagp** [comment]
Date showing above also must be changed from Monday

**Comment by Sujatagp** [comment]
In current release starting a week from Monday. Working as expected hence moving to closed list.

<img width="1151" alt="Screen Shot 2020-04-01 at 4 47 31 PM" src="https://user-images.githubusercontent.com/41627571/78131505-d04e3b80-7438-11ea-884c-1119388e62b6.png">
