### ISSUE TITLE
Display respective day's work hour in monthly calendar

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#60]
- Or show the size of the grid size w.r.t the task's total time.

![Screenshot 2020-02-06 at 12 13 05 PM](https://user-images.githubusercontent.com/8351837/73912250-0a3c0f00-48da-11ea-8b5d-bb68e884ba92.png)

**Comment by anushashetty** [comment]
@vinay-km : Show the total hours on hover of day.

**Comment by Sujatagp** [comment]
In current release showing grid size based on working hours and on hover duration to individual date. Working as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-01 at 5 00 09 PM" src="https://user-images.githubusercontent.com/41627571/78132411-5323c600-743a-11ea-981d-0977fb31f4b7.png">
