### ISSUE TITLE
pixelating or Loosing aspect ratio in uploaded profile picture 

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#62]
![Screenshot 2020-02-06 at 12 47 16 PM](https://user-images.githubusercontent.com/8351837/73914269-f515af00-48de-11ea-86e5-78ebeecd795d.png)

**Comment by Sujatagp** [comment]
Aspect ration of the picture is working as expected hence moving to closed list.

<img width="387" alt="Screen Shot 2020-04-01 at 5 17 46 PM" src="https://user-images.githubusercontent.com/41627571/78133880-da723900-743c-11ea-88ef-fe1ed65b5b6e.png">
