### ISSUE TITLE
Aggregate time not displaying properly

### ISSUE THREAD

**Issue by anushashetty** [IncendiaryCode/TimeTracker#63]
If you sum up the time here it should be 5 hours 01 min so it should be 5:01 but its displaying as 5:1

![image](https://user-images.githubusercontent.com/697216/73935068-c19a4b00-4905-11ea-9f71-1be1f9c91ad5.png)

Even weekly sum up is not proper:
![image](https://user-images.githubusercontent.com/697216/73935327-4be2af00-4906-11ea-88d0-4c4a10d56709.png)

**Comment by Sujatagp** [comment]
In current release agrregate is showing properly at daily and weekly activities. Working as expected hence moving to closed list.

<img width="1259" alt="Screen Shot 2020-02-24 at 12 02 00 PM" src="https://user-images.githubusercontent.com/41627571/75132643-be70ce80-56fd-11ea-8b3c-3caff2cc3375.png">

<img width="1261" alt="Screen Shot 2020-02-24 at 12 03 42 PM" src="https://user-images.githubusercontent.com/41627571/75132647-c2045580-56fd-11ea-8f2c-dc4b8de45f82.png">
