### ISSUE TITLE
Popup time picker for punch out too

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#74]
- CASE: When user forgets to punch out and trying to punch out later in a same day.

**Comment by Sujatagp** [comment]
Added time picker for punch out for the case when we punch out on same day. Working as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-23 at 11 01 10 AM" src="https://user-images.githubusercontent.com/41627571/80062673-e5a71900-8551-11ea-8d0c-0fe85d492aeb.png">
