### ISSUE TITLE
Fetch modules with projects and eliminate the delay in module selection

### ISSUE THREAD

**Issue by Ganeshakumar** [IncendiaryCode/TimeTracker#75]
- Quick selection of the module always goes blank.

**Comment by Sujatagp** [comment]
We are disabling the module until all the modules loads. Working as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-23 at 11 01 10 AM" src="https://user-images.githubusercontent.com/41627571/80063029-9dd4c180-8552-11ea-8008-a93751abcf41.png">
