### ISSUE TITLE
Clicking on date icon,date pop up should display

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#81]
![Capture5232222](https://user-images.githubusercontent.com/41984345/74512047-6a136500-4f2d-11ea-9e25-fc8aa0940a2a.PNG)

**Comment by Sujatagp** [comment]
Clicking on date pop is displaying. Showing as expected hence moving to closed list.

<img width="1280" alt="Screen Shot 2020-04-23 at 11 31 12 AM" src="https://user-images.githubusercontent.com/41627571/80064574-01142300-8556-11ea-9360-620d2bded825.png">
