### ISSUE TITLE
 In Dashboard ,task timings is displaying wrong for the task which is yet to start.

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#82]
**Reproducible steps**
1.Login with valid credentials.
2.Give Punch In time.
3.Add a task and give future start time of today.

**Observation**
- In Dashboard ,task timings is displaying wrong for the task which is yet to start.

**Expectation**
- In Dashboard ,task timings should display properly for the task which is yet to start.
![Capture5222555552](https://user-images.githubusercontent.com/41984345/74513682-2ae71300-4f31-11ea-8294-07575fdccede.PNG)
![Capture25563633](https://user-images.githubusercontent.com/41984345/74513685-2cb0d680-4f31-11ea-84e4-ff05fd0cc725.PNG)

**Comment by Sujatagp** [comment]
As per current design we are not allowing to add only start time for future task. Hence it is moving to closed list.

<img width="1271" alt="Screen Shot 2020-04-22 at 6 27 30 PM" src="https://user-images.githubusercontent.com/41627571/79984597-04140280-84c7-11ea-8e4f-39cc257b425a.png">
