### ISSUE TITLE
PHP error is displaying if you try to access the task link of other user.

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#83]
**Reproducible Steps**
1.Login with valid credentials.
2.Go to the below link . Change the id of the link and search
https://www.brightlightventures.com/timetracker/dev/index.php/user/load_add_task?t_id=160 

**Observation**
-  PHP error is displaying.

![Capture25633](https://user-images.githubusercontent.com/41984345/74525738-de5b0200-4f47-11ea-8192-5620e1dd3545.PNG)

**Expectation**
- PHP error should not display,if you try to access the task link of other user.

**Comment by Sujatagp** [comment]
Showing error message as you don't have task with this id. Working as expected hence moving to closed list.

<img width="1265" alt="Screen Shot 2020-04-22 at 5 50 02 PM" src="https://user-images.githubusercontent.com/41627571/79981182-dd9f9880-84c1-11ea-8a6f-ae41e4f417da.png">
