### ISSUE TITLE
Task Timeline should be sorted by default based by date

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#85]
![Capture5223](https://user-images.githubusercontent.com/41984345/74532301-e2415100-4f54-11ea-95c7-54ef1c995ff3.PNG)

**Comment by Sujatagp** [comment]
In current timeline task timelines are sorting in descending order as expected hence moving to closed list.

<img width="1274" alt="Screen Shot 2020-04-22 at 6 29 45 PM" src="https://user-images.githubusercontent.com/41627571/79984876-6836c680-84c7-11ea-94bf-7c37fa034d54.png">
