### ISSUE TITLE
After adding two timeline in add  task page,clicking on +button, duplicate entry is adding

### ISSUE THREAD

**Issue by gpakshith** [IncendiaryCode/TimeTracker#99]
**Reproducible Steps**
1.Login with valid credential.
2.Click on create task.
3.Add two timeline for the task.
4.Click on+ button.

**Observation** 
- After adding two timeline in add  task page,clicking on +button, duplicate entry is adding.

**Expectation**
- After adding two timeline in add  task page,clicking on +button, duplicate entry is adding.
![Capture32566363666](https://user-images.githubusercontent.com/41984345/75131498-5ae4a200-56f9-11ea-899b-f508e40c2a24.PNG)

![Capture22556363332](https://user-images.githubusercontent.com/41984345/75131496-59b37500-56f9-11ea-91c0-860e8f3ca9a9.PNG)

**Comment by Sujatagp** [comment]
In current release duplicate entry is not adding working as expected hence moving to closing list.
